//
//  L-389.swift
//  LeetCode
//
//  Created by yanglei on 2019/10/20.
//  Copyright © 2019 Lyren. All rights reserved.
//

import Foundation

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/


// 字典计数
/*
func findTheDifference(_ s: String, _ t: String) -> Character {
    var charInfo: [Character: Int] = [:]
    for (_, item) in s.enumerated() {
        charInfo[item] = 1 + (charInfo[item] ?? 0)
    }
    
    for (_, item) in t.enumerated() {
        if let count = charInfo[item], count > 0 {
            charInfo[item] = count - 1
        } else {
            return item
        }
    }
    return "a"
}
*/
